<a href="https://colab.research.google.com/github/pawel-kowal/machine-learning/blob/main/supervised/02_linear_regression/01_linear_regression_normal_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [15]:
X1 = np.array([1,2,3,4,5,6])
y = np.array([3000,3250,3500,3750,4000,4250])
m = len(X1)

print(f"Lata pracy: {X1}")
print(f"Pensja: {y}")
print(f"Liczba próbek: {m}")

Lata pracy: [1 2 3 4 5 6]
Pensja: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [16]:
X1 = X1.reshape(m,1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [17]:
bias = np.ones([m,1])
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [18]:
X = np.append(bias, X1, axis=1)
print(X)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]


In [20]:
np.dot(X.T, X)

array([[ 6., 21.],
       [21., 91.]])

In [25]:
L = np.linalg.inv(np.dot(X.T,X))
P = np.dot(X.T,y)
W = np.dot(L,P)
W

array([2750.,  250.])

## Y = 2750 + 250X

In [29]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1, y)

print(regression.intercept_)
print(regression.coef_[0])

2750.0
250.0
